### ISSUE TITLE
Añadir nuevo nodo regular Docuten

### ISSUE THREAD

**Issue by dgrmunch** [alastria/nodes-redt#2]
Docuten | Azure (2C/8GB/128GB) | enode://b6dbb952941a1bcca7e8dfc5688cc4bdea1e74cae62f0a58fa9462343629f655795f8ee3befb2cc4c03c2bc0b195a3d9652985c31520e4e19cc793bc7b456546@52.142.92.232:21000?discport=0

**Comment by alejandroalffer** [comment]
Ok administrativo, y Ok técnico: zona euro para dicha IP, según GeoIP y tcp/udp disponible para el puerto 21000. Se añade la información en el commit #4ba8ddf, y se comprueba su visualización desde boot node `BOT_DigitelTS_T_2_8_00`
